const BEGIN_PICK_APPLE = "BEGIN_PICK_APPLE";
const DONE_PICK_APPLE = "DONE_PICK_APPLE";
const FAIL_PICK_APPLE = "FAIL_PICK_APPLE";
const EAT_APPLE = "EAT_APPLE";

export {
  BEGIN_PICK_APPLE, DONE_PICK_APPLE, FAIL_PICK_APPLE, EAT_APPLE
}